Fix compile error in 2019.4 caused by use of unavailable language feature
In Unity 2019.4 the presence of this 'static' was causing the following compile error:

    error CS0106: The modifier 'static' is not valid for this item

Local static function isn't available in 2019.4, and by looking at what the
function does the keyword wasn't really needed.